const PROGRAMMER_PRINTING = {
  DOTS: '..',
  EMPTY_STR: '',
  IDX_MARKER: 'x',
  INDEX_BASE: 16,
  MEM_INFO: true,
  MEM_INFO_INDEX: '',
  MEM_INFO_STR: '',
  MIN_COL_WIDTH: 11,
  PAD_STR: ' ',
  PRINT_PREC: 3,
  PRINT_TYPES: true,
  SHOW_MORE: false,
  SPACE_BETWEEN: 2,
  UNDERLINE: ' ',
  UNDERLINE_BOT: true,
};

const MINIMAL_PRINTING = {
  DOTS: '.',
  EMPTY_STR: '',
  IDX_MARKER: '',
  INDEX_BASE: 10,
  MEM_INFO: false,
  MEM_INFO_INDEX: '',
  MEM_INFO_STR: '',
  MIN_COL_WIDTH: 11,
  PAD_STR: ' ',
  PRINT_PREC: 2,
  PRINT_TYPES: false,
  SHOW_MORE: false,
  SPACE_BETWEEN: 2,
  UNDERLINE: ' ',
  UNDERLINE_BOT: true,
};

const DEFAULT_PRINTING = {
  DOTS: '..',
  EMPTY_STR: 'empty',
  IDX_MARKER: '#',
  INDEX_BASE: 10,
  MEM_INFO: true,
  MEM_INFO_INDEX: '',
  MEM_INFO_STR: '',
  MIN_COL_WIDTH: 11,
  PAD_STR: ' ',
  PRINT_PREC: 3,
  PRINT_TYPES: true,
  SHOW_MORE: true,
  SPACE_BETWEEN: 1,
  UNDERLINE: '-',
  UNDERLINE_BOT: true,
};

module.exports = {
  DEFAULT_PRINTING,
  MINIMAL_PRINTING,
  PROGRAMMER_PRINTING,
};
