name: Test CI

on: [push, pull_request]

env:
  DEBUG: 1
  NODE_ENV: development

jobs:
  test:
    name: Test
    strategy:
      max-parallel: 4
      fail-fast: true
      matrix:
        node: ['10', '8']
        os: [windows-latest, ubuntu-lates]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Node Modules
        run: npm install
      - name: Lint Code
        timeout-minutes: 15
        run: npx eslint
      - name: Test Code
        run: npm test
      - name: Audit NPM Packages
        timeout-minutes: 15
        run: npm audit
